name: Compile Arduino Sketch

on:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # CHECKOUT

      - name: Checkout Repo
        uses: actions/checkout@v4

      # INSTALL ARDUINO CLI

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # INSTALL ESP32 CORE

      - name: Install ESP32 Core
        run: |

          arduino-cli core update-index

          arduino-cli core install esp32:esp32

      # CREATE SKETCH

      - name: Create Sketch
        run: |

          mkdir sketch

          cp sketch.txt sketch/sketch.ino

      # AUTO DETECT & INSTALL LIBRARIES

      - name: Detect And Install Libraries
        run: |

          grep "^#include" sketch/sketch.ino \
          | sed 's/#include <//g' \
          | sed 's/>//g' \
          | sed 's/.h//g' \
          > libs.txt

          while read lib; do

            echo "Installing $lib"

            arduino-cli lib install "$lib" || true

          done < libs.txt

      # COMPILE

      - name: Compile Sketch
        run: |

          arduino-cli compile \
          --fqbn esp32:esp32:esp32 \
          sketch

      # UPLOAD BIN

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: sketch/build
